### ISSUE TITLE
Read Travis CI docs 

### ISSUE THREAD

**Issue by mehranhatami** [sunnee5150/music-app#1]
Travis CI is a toolkit in which all of or tests and the whole build workflow runs whenever we push a change to the master. This helps us to have an easier maintaining process.
This task is to get your head around the whole idea behind travis-ci and the way it works, you are not supposed to master it just by reading docs and instead all you should do is trying to get to know it as fast as possible.

You could find really helpful information in this link: [Travis CI User Documentation](http://docs.travis-ci.com/)

**Comment by sunnee5150** [comment]
I did the initial setup, fixed the sample build failure (on the test repo) by fixing the script.  If I understand it so far, travis is a way to test the code against different versions of sw, in our case node.js.....let me know if you want me to dig further!

**Comment by mehranhatami** [comment]
@sunnee5150 this is enough for now and I guess now you know what you need.
>to test the code against different versions...
very close but not thorough. Travis is a continuous integration(CI) server and to learn more about it you could start with reading this article: [Continuous Integration](http://www.thoughtworks.com/continuous-integration), but as far as this task, this was all you needed to do. You could read the article or more about CI in your spare time.
