### ISSUE TITLE
Config your editor

### ISSUE THREAD

**Issue by mehranhatami** [sunnee5150/music-app#3]
The preferable editor is [Sublime Text 3](http://www.sublimetext.com/3).

- Add JSHint and JSLint plugins to your editor 
- Add JavaScript beautifier to your editor and make these changes to its configurations:

```javascript
{
  "indent_size": 2,
  "jslint_happy": true,
  "indent_with_tabs": false,
  "indent_char": " "
}
```

Recommended plugins for this job are:
- [HTML/CSS/JS Prettify](https://github.com/victorporof/Sublime-HTMLPrettify): which supports all the necessary extensions we usually need. 

- [JavaScript Beautify](https://github.com/enginespot/js-beautify-sublime)

- [JsFormat](https://github.com/jdc0589/JsFormat.git)

**Comment by sunnee5150** [comment]
complete!

**Comment by mehranhatami** [comment]
Great Job!
